name: Phase 1 Discovery Workflow
on:
  push:
    paths:
      - 'scripts/phase1/**'
jobs:
  phase1-discovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint -- --fix
      - run: npm run build
      - run: npm test
      - run: npm run discover:phase1
