name: Ubiquitous Language Consistency

on:
  pull_request:
    paths:
      - '**.md'
      - 'scripts/ubiquitous_language_consistency_check.py'
      - 'DDD_Artefacts/docs/v2/ubiquitous-language/guidelines/glossary.md'
      - 'business-model/**'
      - 'DDD_Artefacts/docs/v2/domain-knowledge/core-contexts/**'
  push:
    branches: [main, master]
    paths:
      - '**.md'
      - 'scripts/ubiquitous_language_consistency_check.py'
      - 'DDD_Artefacts/docs/v2/ubiquitous-language/guidelines/glossary.md'
      - 'business-model/**'
      - 'DDD_Artefacts/docs/v2/domain-knowledge/core-contexts/**'

jobs:
  consistency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install inflect
      - name: Run Ubiquitous Language Consistency Check
        run: |
          python scripts/ubiquitous_language_consistency_check.py
